#define PIN1_MOTOR_A 6
#define PIN2_MOTOR_A 7
#define PIN_PWM_MOTOR_A 5
#define PIN1_ENCODER_MOTOR_A 2
#define PIN2_ENCODER_MOTOR_A 2
#define PIN1_MOTOR_B 8
#define PIN2_MOTOR_B 9
#define PIN_PWM_MOTOR_B 5
#define PIN1_ENCODER_MOTOR_B 3
#define PIN2_ENCODER_MOTOR_B 3

#define DIAMETRO_RODA 40
#define PPV 15

int pinSensors[7] = {A0,A1,A2,A3,A4,A5,A6};